version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      
      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'testinguser883' ]; then echo testinguser883; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: env
      
      - run:
          name: Build application container
          command: |
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
      
      - run:
          name: Run application container
          command: |
            docker run --name webapp -d ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
          background: true
      
      - run:
          name: Debugging connectivity to webapp
          command: |
            sleep 5;
            _id=`docker ps --filter=name=webapp -q`;
            _ip=`docker inspect --format "{{ .NetworkSettings.IPAddress }}" $_id`;
            docker pull byrnedo/alpine-curl && docker run byrnedo/alpine-curl $_ip:80;
        
      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
            _id=`docker ps --filter=name=webapp -q`;
            _ip=`docker inspect --format "{{ .NetworkSettings.IPAddress }}" $_id`;
            (
            docker pull owasp/zap2docker-weekly && \
            docker run -t owasp/zap2docker-weekly zap-full-scan.py \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
                -t http://$_ip:80/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )
